plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.6'

repositories { mavenCentral() }

dependencies {
    implementation project(':token')
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

// (Opcional) Ejemplo de task de smoke para este módulo
tasks.register('smokeTest', Test) {
    useJUnitPlatform { includeTags 'smoke' }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}
