plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.6-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':parser')
    implementation project(':common')
    implementation project(':lexer')
    implementation project(':token')
    implementation "com.google.code.gson:gson:2.11.0"

    testImplementation(project(":lexer"))
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}
