plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.3-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':parser')
    implementation project(':common')
    implementation project(':lexer')
    implementation project(':token')

    testImplementation(project(":lexer"))
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}
