plugins {
    id 'org.printscript.conventions'
    id 'application'
}

group = 'org.printscript'
version = '1.4-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'info.picocli:picocli:4.7.6'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    implementation project(':lexer')
    implementation project(':parser')
    implementation project(':interpreter')
    implementation project(':formatter')
    implementation project(':linter')
    implementation project(':common')
    implementation project(':token')
}


application {
    mainClass = 'org.printscript.cli.MainKt'
}
