plugins {
    id 'org.printscript.conventions'
    // id 'application'
}

group = 'org.printscript'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    // implementation project(':lexer')
    // implementation project(':parser')
    // implementation project(':interpreter')
    // implementation project(':formatter')
    // implementation project(':analyzer')
    // implementation 'org.jetbrains.kotlinx:kotlinx-cli:0.3.6'
}

/*
application {
    mainClass = 'org.printscript.cli.MainKt'
}
*/