plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation project(':token')
    implementation project(':common')

    testImplementation project(':lexer')
}

