plugins {
    id 'org.jetbrains.kotlin.jvm'
}

group = 'org.printscript'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation project(':token')

    testImplementation project(':lexer')
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}