plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.4-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation project(':parser')
    implementation project(':common')
}

test {
    minHeapSize = "64m"
    maxHeapSize = "128m"
    jvmArgs "-XX:+HeapDumpOnOutOfMemoryError"
}
