plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '2.8-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':parser')
    implementation project(':common')
    implementation project(':token')
    implementation("com.google.code.gson:gson:2.11.0")
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

