plugins {
    id 'org.printscript.conventions'
}

group = 'org.printscript'
version = '1.6'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation project(':common')
    implementation project(':token')
    implementation project(':lexer')
    implementation project(':parser')
    implementation project(':interpreter')
}

test {
    minHeapSize = "64m"
    maxHeapSize = "128m"
    jvmArgs "-XX:+HeapDumpOnOutOfMemoryError"
    environment "USER", "tais"
    environment "MY_VAR", "valor"
}